

     SUBDIR =
     SUBDIR += ostI_etoys
     SUBDIR += ostI_exupery
     SUBDIR += ostI_funsqueak
     SUBDIR += ostI_newspeak_32
     SUBDIR += ostI_newspeak_64
     SUBDIR += ostI_nuscratch
     SUBDIR += ostI_pharo50_32
     SUBDIR += ostI_pharo50_64
     SUBDIR += ostI_pharo60_32
     SUBDIR += ostI_pharo60_64
     SUBDIR += ostI_pharo70_32
     SUBDIR += ostI_pharo70_64
     SUBDIR += ostI_pharo_mini60
     SUBDIR += ostI_seaside
     SUBDIR += ostI_squeaklight

.include <bsd.port.subdir.mk>
