

     SUBDIR =
     SUBDIR += ostS_squeak1
     SUBDIR += ostS_squeak2
     SUBDIR += ostS_squeak3
     SUBDIR += ostS_squeak39
     SUBDIR += ostS_squeak41
     SUBDIR += ostS_squeak46
     SUBDIR += ostS_squeak50

.include <bsd.port.subdir.mk>
