# $OpenBSD$

N =		nuscratch

V =		20170821
R =		general

T =		NuScratch
D =		${T}${V}-${R}


DISTNAME =	${D}
OST_DISTNAME =	${D}${B}
OST_PKGNAME =	${N}-${V}

HOMEPAGE =	http://pharo.org/

OST_SITE_DIR =	scratch
OST_EXCLUDE =	'__MACOSX*' '*.DS_Store'

OST_UNZIP_OPTS=-q

.include <bsd.port.mk>
