# $OpenBSD$

N =		exupery
V =		0.15
DISTNAME =	${N}-image-${V}
OST_PKGNAME =	${N}-${V}
OST_SITE_DIR =	Exupery/images
OST_OLD_NAME =	squeak
OST_NEW_NAME =	Exupery${V}

post-install: rename

.include <bsd.port.mk>
