

     SUBDIR =
     SUBDIR += ostI_squeak131
     SUBDIR += ostI_squeak28
     SUBDIR += ostI_squeak3102
     SUBDIR += ostI_squeak45
     SUBDIR += ostI_squeak46
     SUBDIR += ostI_squeak51_32
     SUBDIR += ostI_squeak51_64
     SUBDIR += ostI_squeak60_32
     SUBDIR += ostI_squeak60_64

.include <bsd.port.subdir.mk>
