

     SUBDIR =
     SUBDIR += ostV_newspeak_cog_spur
     SUBDIR += ostV_newspeak_stack_spur
     SUBDIR += ostV_pharo_cog_spur
     SUBDIR += ostV_pharo_cog_spur_lowcode
     SUBDIR += ostV_pharo_stack_spur_lowcode
     SUBDIR += ostV_squeak_cog_spur
     SUBDIR += ostV_squeak_cog_vthree
     SUBDIR += ostV_squeak_sista_spur
     SUBDIR += ostV_squeak_stack_spur
     SUBDIR += ostV_squeak_stack_vthree

.include <bsd.port.subdir.mk>
